<<<<<<< HEAD
# Generated by Django 3.1 on 2020-09-25 07:39
=======
>>>>>>> 4f5717f46e02739d71806c9e4b86acd6ae09f313

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=200)),
                ('phone_nubmer', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
