# Generated by Django 3.1 on 2020-09-25 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 17, 39, 43, 184249)),
        ),
    ]
